name: flutter_shared
description: A new Flutter package project.
version: 1.0.1
author:
homepage: distantfutu.re

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_parsed_text: ^1.2.4
  package_info: ^0.4.1
  url_launcher: ^5.5.0
  email_validator: ^1.0.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_icons: ^1.1.0
  bot_toast: ^3.0.0
  intl: ^0.16.1
  native_pdf_renderer: ^2.3.2
  flutter_svg: ^0.18.0
  http: ^0.12.1
  extended_image: ^0.9.0
  random_string: ^2.1.0
  open_file: ^3.0.1
  video_player: ^0.10.11+2
  google_fonts: ^1.1.0
  barcode_widget: ^1.3.0
  barcode_scan: ^3.0.1
  path_provider: ^1.6.11
  device_info: ^0.4.2+4
  image: ^2.1.14
  provider: ^4.3.1
  mime_type: ^0.3.2
  characters: ^1.0.0

  flutter_colorpicker:
    git: git://github.com/sgehrman/flutter_colorpicker
    # path: ../forks/flutter_colorpicker

  barcode_image:
    git:
      url: git://github.com/sgehrman/dart_barcode
      path: image

  share_extend:
    git: git://github.com/sgehrman/ShareExtend

dependency_overrides:
  path: ^1.7.0

dev_dependencies:
  lint: ^1.2.0

flutter:
  uses-material-design: true
