name: flutter_shared
description: A new Flutter package project.
version: 1.0.1
author:
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_parsed_text: ^1.2.5
  package_info: ^0.4.3+2
  url_launcher: ^5.7.10
  email_validator: ^1.0.6
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  flutter_icons: ^1.1.0
  bot_toast: ^3.0.5
  intl: ^0.16.1
  native_pdf_renderer: ^2.4.0
  flutter_svg: ^0.19.2+1
  http: ^0.12.2
  random_string: ^2.1.0
  open_file: ^3.0.3
  video_player: ^1.0.1
  google_fonts: ^1.1.1
  barcode_widget: ^1.5.0
  barcode_scan: ^3.0.1
  path_provider: ^1.6.24
  device_info: ^1.0.0
  image: ^2.1.19
  provider: ^4.3.2+3
  mime_type: ^0.3.2
  characters: ^1.0.0
  shared_preferences: ^0.5.12+4
  crypto: ^2.1.5
  hex: ^0.1.2
  path: ^1.7.0
  bonsoir: ^0.1.2+2

  # extended_image: ^1.3.0
  extended_image:
    git:
      url: git://github.com/fluttercandies/extended_image
      ref: dev

  flutter_colorpicker:
    git: git://github.com/sgehrman/flutter_colorpicker
    # path: ../forks/flutter_colorpicker

  barcode_image:
    git:
      url: git://github.com/sgehrman/dart_barcode
      path: image

  share_extend:
    git: git://github.com/sgehrman/ShareExtend

dev_dependencies:
  lint: ^1.5.1

flutter:
  uses-material-design: true
