name: flutter_shared
description: A new Flutter package project.
version: 1.0.1
author: null
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  barcode_widget: ^2.0.0
  bonsoir: ^1.0.0
  bot_toast: ^4.0.1
  characters: ^1.1.0
  crypto: ^3.0.0
  device_info: ^2.0.0
  email_validator: ^2.0.1
  flutter_icons: ^1.1.0
  simple_animations: ^3.0.2

  flutter_parsed_text: ^2.1.0
  flutter_svg: ^0.21.0-nullsafety.0
  google_fonts: ^2.0.0
  hex: ^0.2.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.13.1
  image: ^3.0.1
  intl: ^0.17.0
  mime_type: ^1.0.0
  native_pdf_renderer: ^3.0.0
  package_info: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  random_string: ^2.2.0-nullsafety
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.2
  video_player: ^2.0.2
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  flare_flutter: ^3.0.0-nullsafety.0
  flutter_archive: ^3.0.0
  extended_image: ^3.0.0
  barcode_image: ^2.0.0
  share_extend: ^1.1.9
  dotted_border: ^2.0.0-nullsafety.0

  flutter_multi_formatter: ^2.0.0
  flutter_colorpicker: ^0.4.0

  open_file:
    git: git://github.com/crazecoder/open_file

dev_dependencies:
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - packages/flutter_shared/assets/animations/treasure.flr
    - packages/flutter_shared/assets/animations/loading.flr
