name: flutter_shared
description: A new Flutter package project.
version: 1.0.1
author: null
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  barcode_widget: ^1.5.0
  bonsoir: ^0.1.3+2
  bot_toast: ^3.0.5
  characters: ^1.0.0
  crypto: ^2.1.5
  device_info: ^1.0.0
  email_validator: ^1.0.6
  flutter_icons: ^1.1.0
  flutter_multi_formatter: ^1.3.6
  simple_animations: ^2.5.1

  flutter_parsed_text: ^1.2.5
  flutter_svg: ^0.19.1
  google_fonts: ^1.1.2
  hex: ^0.1.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.2
  image: ^2.1.19
  intl: ^0.16.1
  mime_type: ^0.3.2
  native_pdf_renderer: ^2.4.0
  open_file: ^3.0.3
  package_info: ^0.4.3+4
  path: ^1.7.0
  path_provider: ^1.6.27
  provider: ^4.3.3
  random_string: ^2.1.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  video_player: ^1.0.1
  flutter_barcode_scanner: ^1.0.2
  flare_flutter: ^2.0.6
  flutter_archive: ^2.0.2
  extended_image: ^1.6.0

  barcode_image:
    git:
      url: git://github.com/sgehrman/dart_barcode
      path: image

  flutter_colorpicker:
    git: git://github.com/sgehrman/flutter_colorpicker
    # path: ../forks/flutter_colorpicker

  share_extend:
    git: git://github.com/sgehrman/ShareExtend

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/flutter_shared/assets/animations/treasure.flr
    - packages/flutter_shared/assets/animations/loading.flr
